"""Adicionado campo na tabela contacto

Revision ID: a80608996410
Revises: 2d8120afc6a7
Create Date: 2026-02-11 18:15:09.199386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80608996410'
down_revision = '2d8120afc6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respodido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.drop_column('respodido')

    # ### end Alembic commands ###
